# Generated by Django 3.1.2 on 2020-10-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleddate',
            name='name',
            field=models.CharField(default='Company name not provided', max_length=200),
        ),
    ]
