# Generated by Django 3.1.3 on 2020-11-05 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='email',
        ),
        migrations.RemoveField(
            model_name='information',
            name='name',
        ),
        migrations.RemoveField(
            model_name='information',
            name='token_id',
        ),
    ]
