# Generated by Django 3.1.2 on 2020-10-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_scheduleddate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleddate',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
