# Generated by Django 3.1.2 on 2020-10-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201026_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleddate',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
