# Generated by Django 3.1.3 on 2020-11-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_register_scheduleapi_timelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.CharField(max_length=256)),
                ('reset_value', models.IntegerField(default=0)),
            ],
        ),
    ]
