# Generated by Django 3.1.2 on 2020-10-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_scheduleddate_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleddate',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
