# Generated by Django 3.1.2 on 2020-10-27 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201026_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleddate',
            name='name',
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.scheduleddate')),
            ],
        ),
    ]
