# Generated by Django 3.1.2 on 2020-10-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201028_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_calls',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='token_id',
            field=models.CharField(max_length=256),
        ),
    ]
