# Generated by Django 3.1.2 on 2020-10-29 10:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20201028_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleddate',
            name='count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
