# Generated by Django 3.1.2 on 2020-10-31 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_userschedules'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSchedules',
            new_name='Schedules',
        ),
    ]
