# Generated by Django 3.1.2 on 2020-11-01 10:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20201031_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='information',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.information'),
            preserve_default=False,
        ),
    ]
