# Generated by Django 3.1.2 on 2020-11-01 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_user_information'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='information',
        ),
    ]
